#!/usr/bin/python

import subprocess, time
ImageNameDecided = 0

##	Deciding the image name
while ImageNameDecided != 1:
	imageName = raw_input("Your output image name:  ")
	print "You said: ", imageName

	nameYN = raw_input("Are you sure? (Type Y or N)").lower()

	if nameYN == 'y':
		ImageNameDecided = 1
	else:
		print ""

##	Date for image name
imageDate = time.strftime("_%d-%m-%Y_%H:%M")

outputFullName = imageName+imageDate

##	Running DCFLDD

proc = subprocess.Popen(["dcfldd", "if=/dev/sdb", "hash=md5,sha256", "md5log=%s"%outputFullName+"_Hash.txt", "sha256log=%s"%outputFullName+"_Sha1.txt", "hashconv=after", "bs=512", "conv=noerror,sync", "of=%s"%outputFullName+".img"])
proc.wait()
